-- Comando SQL completo para criar as tabelas do CodeGen Studio
-- Execute este comando no SQL Editor do seu projeto Supabase

-- =====================================================
-- TABELA DE PERFIS DE USUÁRIO (profiles)
-- =====================================================
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  updated_at TIMESTAMP WITH TIME ZONE,
  
  -- API Keys
  gemini_api_key TEXT,
  github_access_token TEXT,
  openrouter_api_key TEXT,
  
  -- Supabase Integration
  supabase_project_url TEXT,
  supabase_anon_key TEXT,
  supabase_service_key TEXT,
  
  -- Stripe Integration
  stripe_public_key TEXT,
  stripe_secret_key TEXT,
  
  -- Neon Integration
  neon_connection_string TEXT,
  
  -- Google Cloud Platform Integration
  gcp_project_id TEXT,
  gcp_credentials TEXT, -- JSON string of service account key
  
  -- Firebase Firestore Integration
  firebase_project_id TEXT,
  firebase_service_account_key TEXT,
  
  -- Constraints para garantir dados válidos
  CONSTRAINT gemini_api_key_not_empty CHECK (gemini_api_key IS NULL OR gemini_api_key != ''),
  CONSTRAINT github_token_not_empty CHECK (github_access_token IS NULL OR github_access_token != ''),
  CONSTRAINT supabase_url_not_empty CHECK (supabase_project_url IS NULL OR supabase_project_url != ''),
  CONSTRAINT supabase_anon_key_not_empty CHECK (supabase_anon_key IS NULL OR supabase_anon_key != ''),
  CONSTRAINT supabase_service_key_not_empty CHECK (supabase_service_key IS NULL OR supabase_service_key != ''),
  CONSTRAINT stripe_public_key_not_empty CHECK (stripe_public_key IS NULL OR stripe_public_key != ''),
  CONSTRAINT stripe_secret_key_not_empty CHECK (stripe_secret_key IS NULL OR stripe_secret_key != ''),
  CONSTRAINT neon_connection_string_not_empty CHECK (neon_connection_string IS NULL OR neon_connection_string != ''),
  CONSTRAINT gcp_project_id_not_empty CHECK (gcp_project_id IS NULL OR gcp_project_id != ''),
  CONSTRAINT gcp_credentials_not_empty CHECK (gcp_credentials IS NULL OR gcp_credentials != ''),
  CONSTRAINT firebase_project_id_not_empty CHECK (firebase_project_id IS NULL OR firebase_project_id != ''),
  CONSTRAINT firebase_service_account_key_not_empty CHECK (firebase_service_account_key IS NULL OR firebase_service_account_key != '')
);

-- =====================================================
-- TABELA DE PROJETOS (projects)
-- =====================================================
CREATE TABLE IF NOT EXISTS public.projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  name TEXT NOT NULL,
  files JSONB NOT NULL DEFAULT '[]'::jsonb,
  chat_history JSONB NOT NULL DEFAULT '[]'::jsonb,
  env_vars JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  
  -- Constraints para validação
  CONSTRAINT project_name_not_empty CHECK (name != ''),
  CONSTRAINT valid_files CHECK (jsonb_typeof(files) = 'array'),
  CONSTRAINT valid_chat_history CHECK (jsonb_typeof(chat_history) = 'array'),
  CONSTRAINT valid_env_vars CHECK (jsonb_typeof(env_vars) = 'object')
);

-- =====================================================
-- ÍNDICES PARA PERFORMANCE
-- =====================================================
CREATE INDEX IF NOT EXISTS projects_user_id_idx ON public.projects(user_id);
CREATE INDEX IF NOT EXISTS projects_updated_at_idx ON public.projects(updated_at DESC);

-- =====================================================
-- FUNÇÃO PARA ATUALIZAR TIMESTAMP AUTOMATICAMENTE
-- =====================================================
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- =====================================================
-- TRIGGERS PARA UPDATED_AT
-- =====================================================
-- Trigger para profiles
DROP TRIGGER IF EXISTS update_profiles_updated_at ON public.profiles;
CREATE TRIGGER update_profiles_updated_at 
    BEFORE UPDATE ON public.profiles 
    FOR EACH ROW 
    EXECUTE FUNCTION public.update_updated_at_column();

-- Trigger para projects
DROP TRIGGER IF EXISTS update_projects_updated_at ON public.projects;
CREATE TRIGGER update_projects_updated_at 
    BEFORE UPDATE ON public.projects 
    FOR EACH ROW 
    EXECUTE FUNCTION public.update_updated_at_column();

-- =====================================================
-- FUNÇÃO PARA CRIAR PERFIL AUTOMATICAMENTE
-- =====================================================
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, updated_at)
  VALUES (new.id, NOW());
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- =====================================================
-- TRIGGER PARA PERFIL AUTOMÁTICO
-- =====================================================
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- =====================================================
-- ROW LEVEL SECURITY (RLS)
-- =====================================================
-- Habilitar RLS nas tabelas
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;

-- =====================================================
-- POLÍTICAS DE SEGURANÇA PARA PROFILES
-- =====================================================
-- Remover políticas existentes
DROP POLICY IF EXISTS "Users can view own profile" ON public.profiles;
DROP POLICY IF EXISTS "Users can update own profile" ON public.profiles;
DROP POLICY IF EXISTS "Users can insert own profile" ON public.profiles;

-- Criar novas políticas
CREATE POLICY "Users can view own profile"
  ON public.profiles FOR SELECT
  USING (auth.uid() = id);

CREATE POLICY "Users can update own profile"
  ON public.profiles FOR UPDATE
  USING (auth.uid() = id);

CREATE POLICY "Users can insert own profile"
  ON public.profiles FOR INSERT
  WITH CHECK (auth.uid() = id);

-- =====================================================
-- POLÍTICAS DE SEGURANÇA PARA PROJECTS
-- =====================================================
-- Remover políticas existentes
DROP POLICY IF EXISTS "Users can view own projects" ON public.projects;
DROP POLICY IF EXISTS "Users can create own projects" ON public.projects;
DROP POLICY IF EXISTS "Users can update own projects" ON public.projects;
DROP POLICY IF EXISTS "Users can delete own projects" ON public.projects;

-- Criar novas políticas
CREATE POLICY "Users can view own projects"
  ON public.projects FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can create own projects"
  ON public.projects FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own projects"
  ON public.projects FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own projects"
  ON public.projects FOR DELETE
  USING (auth.uid() = user_id);

-- =====================================================
-- PERMISSÕES
-- =====================================================
-- Grant permissions para usuários autenticados
GRANT ALL ON public.profiles TO authenticated;
GRANT ALL ON public.projects TO authenticated;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO authenticated;

-- =====================================================
-- VERIFICAÇÃO
-- =====================================================
-- Verificar se as tabelas foram criadas
SELECT 
  table_name, 
  table_type,
  'Table created successfully' as status
FROM information_schema.tables 
WHERE table_schema = 'public' 
  AND table_name IN ('profiles', 'projects')
ORDER BY table_name;

-- Verificar se as políticas foram criadas
SELECT 
  schemaname,
  tablename,
  policyname,
  'Policy created successfully' as status
FROM pg_policies 
WHERE schemaname = 'public'
ORDER BY tablename, policyname;

-- =====================================================
-- EXEMPLOS DE INSERÇÃO (OPCIONAL)
-- =====================================================
-- Descomente estas linhas para testar (substitua os UUIDs)
-- 
-- INSERT INTO public.profiles (id, gemini_api_key, gcp_project_id, firebase_project_id)
-- VALUES ('seu-user-id-aqui', 'sua-gemini-key', 'seu-gcp-project', 'seu-firebase-project');
-- 
-- INSERT INTO public.projects (user_id, name, files)
-- VALUES ('seu-user-id-aqui', 'Projeto Teste', '[{"name": "index.html", "language": "html", "content": "<h1>Test</h1>"}]');

-- =====================================================
-- LIMPEZA (SE PRECISAR REFAZER)
-- =====================================================
-- Descomente estas linhas APENAS se precisar deletar tudo e recomeçar
-- 
-- DROP TABLE IF EXISTS public.projects CASCADE;
-- DROP TABLE IF EXISTS public.profiles CASCADE;
-- DROP FUNCTION IF EXISTS public.handle_new_user();
-- DROP FUNCTION IF EXISTS public.update_updated_at_column();
