CREATE TABLE public.projects (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id uuid NOT NULL,
    name text NOT NULL,
    files jsonb NOT NULL,
    chat_history jsonb NOT NULL,
    env_vars jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;

CREATE UNIQUE INDEX projects_pkey ON public.projects USING btree (id);

ALTER TABLE public.projects ADD CONSTRAINT projects_pkey PRIMARY KEY (id);
ALTER TABLE public.projects ADD CONSTRAINT projects_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;