-- Schema para o CodeGen Studio
-- Execute este SQL no painel do Supabase em SQL Editor

-- Tabela de perfis de usuário (profiles)
CREATE TABLE IF NOT EXISTS profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  updated_at TIMESTAMP WITH TIME ZONE,
  gemini_api_key TEXT,
  github_access_token TEXT,
  supabase_project_url TEXT,
  supabase_anon_key TEXT,
  supabase_service_key TEXT,
  stripe_public_key TEXT,
  stripe_secret_key TEXT,
  neon_connection_string TEXT,
  openrouter_api_key TEXT,
  gcp_project_id TEXT,
  gcp_credentials TEXT, -- JSON string of service account key
  firebase_project_id TEXT,
  firebase_service_account_key TEXT,
  
  -- Constraints para garantir que os campos sensíveis não sejam nulos quando usados
  CONSTRAINT gemini_api_key_not_empty CHECK (gemini_api_key IS NULL OR gemini_api_key != ''),
  CONSTRAINT github_token_not_empty CHECK (github_access_token IS NULL OR github_access_token != ''),
  CONSTRAINT supabase_url_not_empty CHECK (supabase_project_url IS NULL OR supabase_project_url != ''),
  CONSTRAINT supabase_anon_key_not_empty CHECK (supabase_anon_key IS NULL OR supabase_anon_key != ''),
  CONSTRAINT supabase_service_key_not_empty CHECK (supabase_service_key IS NULL OR supabase_service_key != ''),
  CONSTRAINT stripe_public_key_not_empty CHECK (stripe_public_key IS NULL OR stripe_public_key != ''),
  CONSTRAINT stripe_secret_key_not_empty CHECK (stripe_secret_key IS NULL OR stripe_secret_key != ''),
  CONSTRAINT neon_connection_string_not_empty CHECK (neon_connection_string IS NULL OR neon_connection_string != ''),
  CONSTRAINT openrouter_api_key_not_empty CHECK (openrouter_api_key IS NULL OR openrouter_api_key != ''),
  CONSTRAINT gcp_project_id_not_empty CHECK (gcp_project_id IS NULL OR gcp_project_id != ''),
  CONSTRAINT gcp_credentials_not_empty CHECK (gcp_credentials IS NULL OR gcp_credentials != ''),
  CONSTRAINT firebase_project_id_not_empty CHECK (firebase_project_id IS NULL OR firebase_project_id != ''),
  CONSTRAINT firebase_service_account_key_not_empty CHECK (firebase_service_account_key IS NULL OR firebase_service_account_key != '')
);

-- Tabela de projetos (projects)
CREATE TABLE IF NOT EXISTS projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  name TEXT NOT NULL,
  files JSONB NOT NULL DEFAULT '[]'::jsonb,
  chat_history JSONB NOT NULL DEFAULT '[]'::jsonb,
  env_vars JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  
  -- Constraints
  CONSTRAINT project_name_not_empty CHECK (name != ''),
  CONSTRAINT valid_files CHECK (jsonb_typeof(files) = 'array'),
  CONSTRAINT valid_chat_history CHECK (jsonb_typeof(chat_history) = 'array'),
  CONSTRAINT valid_env_vars CHECK (jsonb_typeof(env_vars) = 'object')
);

-- Índices para melhor performance
CREATE INDEX IF NOT EXISTS projects_user_id_idx ON projects(user_id);
CREATE INDEX IF NOT EXISTS projects_updated_at_idx ON projects(updated_at DESC);

-- Trigger para atualizar o campo updated_at automaticamente
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_profiles_updated_at 
    BEFORE UPDATE ON profiles 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_projects_updated_at 
    BEFORE UPDATE ON projects 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();

-- Function para criar perfil automaticamente quando um usuário é criado
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, updated_at)
  VALUES (new.id, NOW());
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger para automaticamente criar perfil quando usuário se registra
CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- Row Level Security (RLS) Policies
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE projects ENABLE ROW LEVEL SECURITY;

-- Políticas para a tabela profiles
CREATE POLICY "Users can view own profile"
  ON profiles FOR SELECT
  USING (auth.uid() = id);

CREATE POLICY "Users can update own profile"
  ON profiles FOR UPDATE
  USING (auth.uid() = id);

CREATE POLICY "Users can insert own profile"
  ON profiles FOR INSERT
  WITH CHECK (auth.uid() = id);

-- Políticas para a tabela projects
CREATE POLICY "Users can view own projects"
  ON projects FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can create own projects"
  ON projects FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own projects"
  ON projects FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own projects"
  ON projects FOR DELETE
  USING (auth.uid() = user_id);

-- Grant permissions
GRANT ALL ON profiles TO authenticated;
GRANT ALL ON projects TO authenticated;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO authenticated;

-- Comente estas linhas se precisar acesso público (não recomendado para dados sensíveis)
-- GRANT SELECT ON profiles TO anon;
-- GRANT SELECT ON projects TO anon;
